BLENDER="C:\Program Files\Blender Foundation\Blender 4.1\blender.exe"
DIST=../dist

all : \
    $(DIST)/graveyard.pnct \
    $(DIST)/graveyard.scene \

$(DIST)/graveyard.scene : graveyard.blend export-scene.py
	$(BLENDER) --background --python export-scene.py -- "graveyard.blend:Collection" "$(DIST)/graveyard.scene"

$(DIST)/graveyard.pnct : graveyard.blend export-meshes.py
	$(BLENDER) --background --python export-meshes.py -- "graveyard.blend:Collection" "$(DIST)/graveyard.pnct"
